import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — WorkTeams",
  description: "How WorkTeams collects, uses, and protects your information.",
};

const section = { marginBottom: 22 };
const h = { fontSize: "1.15rem", margin: "0 0 8px" };
const p = { lineHeight: 1.7, color: "var(--ink-soft)" };

export default function PrivacyPage() {
  return (
    <main className="site-shell" style={{ maxWidth: 760 }}>
      <p className="eyebrow">LEGAL</p>
      <h1 style={{ fontSize: "2rem", margin: "6px 0 4px" }}>Privacy Policy</h1>
      <p style={{ color: "var(--muted)", marginBottom: 26 }}>Last updated: October 1, 2026</p>

      <div style={section}>
        <h2 style={h}>What WorkTeams is</h2>
        <p style={p}>
          WorkTeams is workforce software for cleaning companies. Each company&apos;s
          data is kept separate: employees can only see the company (or companies)
          they belong to, and ordinary employees never see pay rates, other
          employees&apos; hours, or client access details.
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>Information we collect</h2>
        <p style={p}>
          <strong>Account information:</strong> your email address and the name you
          provide when you create an account or are invited to a company.
          <br />
          <strong>Company data you enter:</strong> locations, schedules, time-clock
          entries (including GPS coordinates captured at clock-in/out when you
          allow it), inspection notes and photos, messages, bids, work orders,
          supplies, and training progress.
          <br />
          <strong>Billing information:</strong> handled by Stripe, our payment
          processor. We store your subscription tier and status, but never your
          full card number.
          <br />
          <strong>Technical data:</strong> basic logs needed to run and secure the
          service (for example, request times and error reports).
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>How we use it</h2>
        <p style={p}>
          We use your information to provide the service — running schedules, the
          time clock, payroll-ready hour reports, inspections, messaging, and
          billing for your subscription. We do not sell your personal information
          and we do not use it for advertising.
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>Who can see your data</h2>
        <p style={p}>
          Owners and admins of your company can see company data, including pay
          rates and reports. Employees see only what they need for their own work.
          We share data only with the service providers required to run WorkTeams
          (hosting, database, and Stripe for payments), and only as needed to
          provide the service. We disclose information if required by law.
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>Client portal links</h2>
        <p style={p}>
          Companies may share read-only client portal links for a location. Anyone
          with the link can see upcoming visits, recent inspection scores, and open
          work orders for that location — no financial or staff details are shown.
          Links can be revoked or regenerated by the company at any time.
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>Data retention and deletion</h2>
        <p style={p}>
          Company data is kept while the account is active. If your company
          account is closed, you may request deletion of your company&apos;s data.
          To request access, correction, or deletion of your personal information,
          contact the owner of your company or reach us through the contact
          information in the app.
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>Security</h2>
        <p style={p}>
          We use industry-standard measures — encrypted connections, authenticated
          access, and database-level access controls — to protect your information.
          No system is perfectly secure, and you are responsible for keeping your
          password private.
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>Children</h2>
        <p style={p}>
          WorkTeams is a business tool and is not directed at children under 13.
        </p>
      </div>

      <div style={section}>
        <h2 style={h}>Changes to this policy</h2>
        <p style={p}>
          If we make material changes, we will update the date above and, where
          appropriate, notify account owners.
        </p>
      </div>

      <p style={{ marginTop: 30 }}>
        <Link href="/" style={{ color: "var(--brand-deep)", fontWeight: 700 }}>← Back to WorkTeams</Link>
      </p>
    </main>
  );
}
